name: CI/CD
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Deploying to Vercel via Deploy Hook"
      - run: curl -X POST ${{ secrets.VERCEL_DEPLOY_HOOK_URL }}
